# Pandas 筛选练习 01：筛选高温故障设备

## 练习背景

现有一张设备运行记录表，每一行代表一台设备的一次运行记录。

## 任务

筛选同时满足以下条件的记录：

- `status` 等于 `ERROR`
- `temperature` 大于或等于 80

结果只保留以下字段：

- `record_id`
- `site`
- `device_type`
- `status`
- `temperature`

将筛选结果保存为：

`df_result`

## 要求

- 使用布尔掩码完成筛选。
- 两个条件之间使用 `&`。
- 每个条件必须分别放在括号中。
- 使用 `.loc[]` 同时完成行筛选和列选择。
- 不使用 `query()`。
- 不使用循环。
- 不直接修改 `df_raw`。

In [11]:
import pandas as pd

data = {
    "record_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "site": [
        "R34", "R34", "R35", "R35", "R36",
        "R36", "R37", "R37", "R38", "R38"
    ],
    "device_type": [
        "VIS", "RVR", "VIS", "WIND", "VIS",
        "RVR", "WIND", "VIS", "RVR", "WIND"
    ],
    "status": [
        "NORMAL", "ERROR", "ERROR", "WARNING", "ERROR",
        "NORMAL", "ERROR", "WARNING", "ERROR", "NORMAL"
    ],
    "temperature": [
        62, 78, 86, 81, 91,
        73, 84, 76, 95, 68
    ]
}

df_raw = pd.DataFrame(data)

df_raw

   record_id site device_type   status  temperature
0          1  R34         VIS   NORMAL           62
1          2  R34         RVR    ERROR           78
2          3  R35         VIS    ERROR           86
3          4  R35        WIND  WARNING           81
4          5  R36         VIS    ERROR           91
5          6  R36         RVR   NORMAL           73
6          7  R37        WIND    ERROR           84
7          8  R37         VIS  WARNING           76
8          9  R38         RVR    ERROR           95
9         10  R38        WIND   NORMAL           68

In [12]:
# df_result = (
#     df_raw
#     .loc[
#         (df_raw["status"] == "ERROR")
#         & (df_raw["temperature"] >= 80),
#         ["record_id", "site", "device_type", "status", "temperature"]
#     ]
#     .sort_values(by="record_id")
#     .reset_index(drop=True)
# )

# df_result

## 练习 02：筛选指定站点的设备记录

### 任务

从 `df_raw` 中筛选站点属于以下任意一个值的记录：

- `R34`
- `R36`

结果只保留以下字段：

- `record_id`
- `site`
- `device_type`
- `status`
- `temperature`

将结果保存为：

```python
df_result
```

### 要求

- 必须使用 `.isin()`。
- 必须使用 `.loc[]` 同时完成行筛选和列选择。
- 按 `record_id` 升序排列。
- 排序后重新整理索引。
- 不使用 `|` 分别连接两个站点条件。
- 不使用 `query()`。

In [13]:
# df_result = (
#     df_raw
#     .loc[df_raw['site'].isin(['R34','R36']),["record_id", "site", "device_type", "status", "temperature"]]
#     .sort_values(by='record_id')
#     .reset_index(drop=True)
# )
# df_result

## 练习 03：筛选指定温度区间的设备记录

### 任务

从 `df_raw` 中筛选温度位于 **70℃ 到 85℃之间** 的记录，包括 70 和 85。

结果只保留以下字段：

- `record_id`
- `site`
- `device_type`
- `status`
- `temperature`

将结果保存为：

```python
df_result
```

### 要求

- 必须使用 `.between()`。
- 必须使用 `.loc[]` 同时完成行筛选和列选择。
- 按 `temperature` 降序排列。
- 排序后重新整理索引。
- 不使用 `>=` 和 `<=` 手动组合区间条件。
- 不使用 `query()`。

In [ ]:
# df_result = (
#     df_raw
#     .loc[
#         df_raw["temperature"].between(70, 85),
#         ["record_id", "site", "device_type", "status", "temperature"]
#     ]
#     .sort_values(
#         by="temperature",
#         ascending=False
#     )
#     .reset_index(drop=True)
# )

# df_result

   record_id site device_type   status  temperature
0          7  R37        WIND    ERROR           84
1          4  R35        WIND  WARNING           81
2          2  R34         RVR    ERROR           78
3          8  R37         VIS  WARNING           76
4          6  R36         RVR   NORMAL           73

## 练习 04：筛选非正常状态设备

### 任务

从 `df_raw` 中筛选 `status` 不是 `NORMAL` 的记录。

结果只保留以下字段：

- `record_id`
- `site`
- `device_type`
- `status`
- `temperature`

将结果保存为：

```python
df_result
```

### 要求

- 必须先使用 `.eq("NORMAL")` 判断正常状态。
- 必须使用 `~` 对条件取反。
- 使用 `.loc[]` 同时完成行筛选和列选择。
- 按 `record_id` 升序排列。
- 排序后重新整理索引。
- 不使用 `!=`。
- 不使用 `query()`。

In [ ]:
# df_result = (
#     df_raw
#     .loc[
#         ~df_raw['status'].eq('NORMAL'),
#         ["record_id", "site", "device_type", "status", "temperature"]
#     ]
#     .sort_values(
#         by="record_id",
#         ascending=False
#     )
#     .reset_index(drop=True)
# )
# df_result

   record_id site device_type   status  temperature
0          9  R38         RVR    ERROR           95
1          8  R37         VIS  WARNING           76
2          7  R37        WIND    ERROR           84
3          5  R36         VIS    ERROR           91
4          4  R35        WIND  WARNING           81
5          3  R35         VIS    ERROR           86
6          2  R34         RVR    ERROR           78

## 练习 05：标记需要重点检查的设备

### 任务

创建 `df_raw` 的副本：

```python
df_result
```

在 `df_result` 中新增字段：

```text
inspection_flag
```

先将所有记录的 `inspection_flag` 设置为：

```text
NORMAL
```

然后将同时满足以下条件的记录修改为：

```text
CHECK
```

条件：

- `status` 等于 `ERROR`
- `temperature` 大于或等于 80

### 要求

- 不允许直接修改 `df_raw`。
- 必须使用 `.copy()` 创建 `df_result`。
- 必须使用布尔掩码表示条件。
- 两个条件之间使用 `&`。
- 每个条件分别放在括号中。
- 必须使用 `.loc[]` 完成条件赋值。
- 不使用循环。
- 不使用 `apply()`。
- 最后输出完整的 `df_result`。

In [29]:
df_result = df_raw.copy()

df_result['inspection_flag'] = 'NORMAL'

check_mask = (df_result['status'] == 'ERROR') & (df_result['temperature'] >= 80)

df_result.loc[check_mask,'inspection_flag'] = 'CHECK'

df_result

   record_id site device_type   status  temperature inspection_flag
0          1  R34         VIS   NORMAL           62          NORMAL
1          2  R34         RVR    ERROR           78          NORMAL
2          3  R35         VIS    ERROR           86           CHECK
3          4  R35        WIND  WARNING           81          NORMAL
4          5  R36         VIS    ERROR           91           CHECK
5          6  R36         RVR   NORMAL           73          NORMAL
6          7  R37        WIND    ERROR           84           CHECK
7          8  R37         VIS  WARNING           76          NORMAL
8          9  R38         RVR    ERROR           95           CHECK
9         10  R38        WIND   NORMAL           68          NORMAL