In [1]:
import pandas as pd

df = pd.DataFrame({
    "record_id": [101,102,103,104,105,106,107,108,109,110],
    "site": ["R34","R36","R34","R35","R34","R36","R35","R34","R36","R35"],
    "status": ["NORMAL","ERROR","ERROR","NORMAL","ERROR","NORMAL","ERROR","NORMAL","ERROR","ERROR"],
    "temperature": [68,82,91,75,87,72,95,69,81,88],
    "visibility": [1200,800,500,1500,600,1100,400,1300,750,550]
})

print(df)

   record_id site  status  temperature  visibility
0        101  R34  NORMAL           68        1200
1        102  R36   ERROR           82         800
2        103  R34   ERROR           91         500
3        104  R35  NORMAL           75        1500
4        105  R34   ERROR           87         600
5        106  R36  NORMAL           72        1100
6        107  R35   ERROR           95         400
7        108  R34  NORMAL           69        1300
8        109  R36   ERROR           81         750
9        110  R35   ERROR           88         550

### ① 使用布尔索引 `[]`

筛选：

- site 为 `"R34"`

保存为：

```python
r34_df
```

---

In [2]:
r34_df = df[df['site'] == 'R34']
r34_df

   record_id site  status  temperature  visibility
0        101  R34  NORMAL           68        1200
2        103  R34   ERROR           91         500
4        105  R34   ERROR           87         600
7        108  R34  NORMAL           69        1300

### ② 使用多个条件

筛选：

- site 为 `"R34"`
- 并且 status 为 `"ERROR"`

保存为：

```python
error_df
```

In [3]:
error_df = df[(df['site'] == 'R34') & (df['status'] == 'ERROR')]
error_df

   record_id site status  temperature  visibility
2        103  R34  ERROR           91         500
4        105  R34  ERROR           87         600

### ③ 使用 `query()`

完成与②相同的筛选。

保存为：

```python
error_query
```

In [4]:
error_query = df.query("site == 'R34' & status == 'ERROR'")
error_query

   record_id site status  temperature  visibility
2        103  R34  ERROR           91         500
4        105  R34  ERROR           87         600

### ④ 使用 `isin()`

筛选：

只保留：

- R34
- R35

两个站点。

保存为：

```python
site_df
```

In [6]:
site_df = df[df['site'].isin(['R34','R35'])]
site_df

   record_id site  status  temperature  visibility
0        101  R34  NORMAL           68        1200
2        103  R34   ERROR           91         500
3        104  R35  NORMAL           75        1500
4        105  R34   ERROR           87         600
6        107  R35   ERROR           95         400
7        108  R34  NORMAL           69        1300
9        110  R35   ERROR           88         550

### ⑤ 使用 `between()`

筛选：

temperature 在

```
70~90
```

之间（包含70和90）。

保存为：

```python
temp_df
```

In [11]:
temp_df = df[df['temperature'].between(70,90)]
temp_df

   record_id site  status  temperature  visibility
1        102  R36   ERROR           82         800
3        104  R35  NORMAL           75        1500
4        105  R34   ERROR           87         600
5        106  R36  NORMAL           72        1100
8        109  R36   ERROR           81         750
9        110  R35   ERROR           88         550

### ⑥ 使用 `where()`

将：

temperature 小于 80

的数据替换为 NaN。

保存为：

```python
temp_where
```

In [9]:
temp_where = df.where(df['temperature'] >= 80)
temp_where

   record_id site status  temperature  visibility
0        NaN  NaN    NaN          NaN         NaN
1      102.0  R36  ERROR         82.0       800.0
2      103.0  R34  ERROR         91.0       500.0
3        NaN  NaN    NaN          NaN         NaN
4      105.0  R34  ERROR         87.0       600.0
5        NaN  NaN    NaN          NaN         NaN
6      107.0  R35  ERROR         95.0       400.0
7        NaN  NaN    NaN          NaN         NaN
8      109.0  R36  ERROR         81.0       750.0
9      110.0  R35  ERROR         88.0       550.0

### ⑦ 使用 `mask()`

将：

temperature 大于等于 80

的数据替换为 NaN。

保存为：

```python
temp_mask
```

In [10]:
temp_mask = df.mask(df['temperature'] >= 80)
temp_mask

   record_id site  status  temperature  visibility
0      101.0  R34  NORMAL         68.0      1200.0
1        NaN  NaN     NaN          NaN         NaN
2        NaN  NaN     NaN          NaN         NaN
3      104.0  R35  NORMAL         75.0      1500.0
4        NaN  NaN     NaN          NaN         NaN
5      106.0  R36  NORMAL         72.0      1100.0
6        NaN  NaN     NaN          NaN         NaN
7      108.0  R34  NORMAL         69.0      1300.0
8        NaN  NaN     NaN          NaN         NaN
9        NaN  NaN     NaN          NaN         NaN