In [1]:
import pandas as pd


df = pd.DataFrame({
    "record_id": [101, 102, 103, 104, 105, 106],
    "site": ["R34", "R36", "R34", "R35", "R34", "R36"],
    "status": ["NORMAL", "ERROR", "ERROR", "NORMAL", "ERROR", "NORMAL"],
    "temperature": [68, 82, 91, 75, 87, 72],
    "visibility": [1200, 800, 500, 1500, 600, 1100]
})

print(df)

   record_id site  status  temperature  visibility
0        101  R34  NORMAL           68        1200
1        102  R36   ERROR           82         800
2        103  R34   ERROR           91         500
3        104  R35  NORMAL           75        1500
4        105  R34   ERROR           87         600
5        106  R36  NORMAL           72        1100

# Pandas 日练 01：选择与索引

请完成以下操作：

1. 使用 `[]` 取出 `site` 这一列，保存为 `site_series`。

In [4]:
site_series = df['site']
site_series

0    R34
1    R36
2    R34
3    R35
4    R34
5    R36
Name: site, dtype: str

2. 使用双层 `[]` 取出以下三列，保存为 `basic_info`：
   - `record_id`
   - `site`
   - `status`

In [11]:
basic_info = df[['record_id','site','status']]
basic_info

   record_id site  status
0        101  R34  NORMAL
1        102  R36   ERROR
2        103  R34   ERROR
3        104  R35  NORMAL
4        105  R34   ERROR
5        106  R36  NORMAL

3. 使用 `loc` 选出：
   - `site` 为 `R34`
   - 只保留 `record_id`、`status`、`temperature`
   
   保存为 `r34_records`。

In [12]:
r34_records = df.loc[df['site'] == 'R34',['record_id','status','temperature']]
r34_records

   record_id  status  temperature
0        101  NORMAL           68
2        103   ERROR           91
4        105   ERROR           87

4. 使用 `iloc` 取出：
   - 前 3 行
   - 第 1、2、4 列
   
   保存为 `first_three`。

In [18]:
first_three = df.iloc[:3,[0,1,3]]
first_three

   record_id site  temperature
0        101  R34           68
1        102  R36           82
2        103  R34           91

5. 使用 `at` 读取索引为 `2` 的记录中的 `temperature`，保存为 `temperature_at_2`。

In [22]:
temperature_at_2 = df.at[2, "temperature"]

print(temperature_at_2)

91

6. 使用 `iat` 读取第 4 行、第 5 列的数据，保存为 `value_by_position`。

In [21]:
value_by_position = df.iat[3, 4]

print(value_by_position)

1500