In [ ]:
import pandas as pd

df = pd.DataFrame({
    "record_id":[101,102,103,104,105,106,107,108,103,105,110,111],
    "site":["R34","R36","R35","R34","R35","R36","R34","R35","R35","R35","R34","R36"],
    "status":["ERROR","NORMAL","ERROR","ERROR","NORMAL","ERROR","ERROR","NORMAL","ERROR","NORMAL","ERROR","ERROR"],
    "temperature":[72,65,88,91,75,83,79,86,88,75,70,92],
    "visibility":[800,1200,550,680,900,450,520,610,550,900,580,700]
})

print(df)

### 任务1

找出所有重复的数据。

重复规则：

- record_id
- site

两列完全相同。

要求：

保留所有重复记录（包括第一次出现）。

保存为：

```python
duplicate_records
```

---

In [ ]:
duplicate_records = df[df.duplicated(subset=['record_id','site'],keep=False)]
duplicate_records

### 任务2

删除重复记录。

要求：

仅保留第一次出现的数据。

保存为：

```python
clean_df
```

---

In [ ]:
clean_df = df.drop_duplicates(subset=['record_id','site'],keep='first')
clean_df

### 任务3

按照：

① site 升序

② temperature 降序

进行排序。

保存为：

```python
sorted_df
```

---

In [ ]:
sorted_df = df.sort_values(by=['site','temperature'],ascending=[True,False])
sorted_df

### 任务4

找出温度最高的 3 条记录。

保存为：

```python
top3_temp
```

---

In [20]:
top3_temp = (
    df
    .sort_values(by='temperature',ascending=False)
    .reset_index(drop=True)
    .head(3)
)
top3_temp

   record_id site status  temperature  visibility
0        111  R36  ERROR           92         700
1        104  R34  ERROR           91         680
2        103  R35  ERROR           88         550

In [25]:
top3_temp = df.nlargest(3,'temperature').reset_index(drop=True)
top3_temp

   record_id site status  temperature  visibility
0        111  R36  ERROR           92         700
1        104  R34  ERROR           91         680
2        103  R35  ERROR           88         550

### 任务5

找出能见度最低的 2 条记录。

保存为：

```python
lowest2_visibility
```

---

In [23]:
lowest2_visibility =  (
    df
    .sort_values(by='visibility',ascending=True)
    .reset_index(drop=True)
    .iloc[:2]
)
lowest2_visibility

   record_id site status  temperature  visibility
0        106  R36  ERROR           83         450
1        107  R34  ERROR           79         520

In [26]:
lowest2_visibility = (
    df
    .nsmallest(
        2,
        'visibility'
    )
    .reset_index(drop=True)
)
lowest2_visibility

   record_id site status  temperature  visibility
0        106  R36  ERROR           83         450
1        107  R34  ERROR           79         520