In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "record_id":[101,102,103,104,105,106,107,108,109,110],
    "site":["R34","R36","R35","R34","R35","R36","R34","R35","R36","R34"],
    "status":["ERROR","NORMAL",np.nan,"ERROR","NORMAL","ERROR","ERROR",np.nan,"NORMAL","ERROR"],
    "temperature":[72,np.nan,88,91,np.nan,83,79,86,73,np.nan],
    "visibility":[800,1200,np.nan,680,900,450,np.nan,610,1000,580]
})

print(df)

   record_id site  status  temperature  visibility
0        101  R34   ERROR         72.0       800.0
1        102  R36  NORMAL          NaN      1200.0
2        103  R35     NaN         88.0         NaN
3        104  R34   ERROR         91.0       680.0
4        105  R35  NORMAL          NaN       900.0
5        106  R36   ERROR         83.0       450.0
6        107  R34   ERROR         79.0         NaN
7        108  R35     NaN         86.0       610.0
8        109  R36  NORMAL         73.0      1000.0
9        110  R34   ERROR          NaN       580.0

### 任务1

统计每一列缺失值的数量。

保存为：

```python
missing_count
```

---

In [4]:
missing_count = df.isna().sum()
missing_count

record_id      0
site           0
status         2
temperature    3
visibility     2
dtype: int64

### 任务2

找出：

**temperature 缺失**

或者

**visibility 缺失**

的所有记录。

保存为：

```python
missing_records
```

---

In [20]:
missing_records = df[
    df["temperature"].isna()
    | df["visibility"].isna()
]

missing_records

   record_id site  status  temperature  visibility
1        102  R36  NORMAL          NaN      1200.0
2        103  R35     NaN         88.0         NaN
4        105  R35  NORMAL          NaN       900.0
6        107  R34   ERROR         79.0         NaN
9        110  R34   ERROR          NaN       580.0

### 任务3

对于：

temperature 缺失

使用

```
同站点(site)的平均温度
```

进行填充。

保存结果为：

```python
filled_df
```

---

In [21]:
filled_df = (
    df
    .assign(
        avg_temp=lambda x: (
            x.groupby("site")["temperature"]
             .transform("mean")
        ),
        temperature=lambda x: (
            x["temperature"].fillna(x["avg_temp"])
        )
    )
    .drop(columns="avg_temp")
)
filled_df

   record_id site  status  temperature  visibility
0        101  R34   ERROR    72.000000       800.0
1        102  R36  NORMAL    78.000000      1200.0
2        103  R35     NaN    88.000000         NaN
3        104  R34   ERROR    91.000000       680.0
4        105  R35  NORMAL    87.000000       900.0
5        106  R36   ERROR    83.000000       450.0
6        107  R34   ERROR    79.000000         NaN
7        108  R35     NaN    86.000000       610.0
8        109  R36  NORMAL    73.000000      1000.0
9        110  R34   ERROR    80.666667       580.0

### 任务4

由于：

status

属于业务字段。

如果：

status 缺失

认为这条数据无法分析。

请删除这些记录。

保存为：

```python
clean_df
```

---

In [22]:
clean_df = (
    filled_df
    .dropna(subset=["status"])
    .reset_index(drop=True)
)

clean_df

   record_id site  status  temperature  visibility
0        101  R34   ERROR    72.000000       800.0
1        102  R36  NORMAL    78.000000      1200.0
2        104  R34   ERROR    91.000000       680.0
3        105  R35  NORMAL    87.000000       900.0
4        106  R36   ERROR    83.000000       450.0
5        107  R34   ERROR    79.000000         NaN
6        109  R36  NORMAL    73.000000      1000.0
7        110  R34   ERROR    80.666667       580.0

### 任务5

输出：

最终数据中

是否还存在缺失值。

返回：

```python
True
```

或

```python
False
```

保存为：

```python
has_missing
```

---

In [24]:
has_missing = clean_df.isna().any().any()
has_missing

np.True_