In [17]:
import pandas as pd

df = pd.DataFrame({
    "record_id":[101,102,103,104,105,106,107,108,109,110,111,112],
    "site":["R34","R36","R35","R34","R35","R36","R34","R35","R36","R34","R35","R34"],
    "status":["ERROR","NORMAL","ERROR","ERROR","NORMAL","ERROR","ERROR","ERROR","NORMAL","ERROR","ERROR","NORMAL"],
    "temperature":[72,65,88,91,75,83,79,86,73,70,92,81],
    "visibility":[800,1200,550,680,900,450,520,610,1000,580,700,1300]
})

print(df)

    record_id site  status  temperature  visibility
0         101  R34   ERROR           72         800
1         102  R36  NORMAL           65        1200
2         103  R35   ERROR           88         550
3         104  R34   ERROR           91         680
4         105  R35  NORMAL           75         900
5         106  R36   ERROR           83         450
6         107  R34   ERROR           79         520
7         108  R35   ERROR           86         610
8         109  R36  NORMAL           73        1000
9         110  R34   ERROR           70         580
10        111  R35   ERROR           92         700
11        112  R34  NORMAL           81        1300

### 任务1

只分析：

- R34
- R35

两个站点。

In [18]:
df = df[df['site'].isin(['R34','R35'])]
df

    record_id site  status  temperature  visibility
0         101  R34   ERROR           72         800
2         103  R35   ERROR           88         550
3         104  R34   ERROR           91         680
4         105  R35  NORMAL           75         900
6         107  R34   ERROR           79         520
7         108  R35   ERROR           86         610
9         110  R34   ERROR           70         580
10        111  R35   ERROR           92         700
11        112  R34  NORMAL           81        1300

### 任务2

只保留：

状态为

```
ERROR
```

的数据。

---

In [19]:
df = df[df['status'] == 'ERROR']
df

    record_id site status  temperature  visibility
0         101  R34  ERROR           72         800
2         103  R35  ERROR           88         550
3         104  R34  ERROR           91         680
6         107  R34  ERROR           79         520
7         108  R35  ERROR           86         610
9         110  R34  ERROR           70         580
10        111  R35  ERROR           92         700

### 任务3

仪器规定：

只有温度在

```
70~90℃
```

In [20]:
df = df[df['temperature'].between(70,90)]
df

   record_id site status  temperature  visibility
0        101  R34  ERROR           72         800
2        103  R35  ERROR           88         550
6        107  R34  ERROR           79         520
7        108  R35  ERROR           86         610
9        110  R34  ERROR           70         580

### 任务4

由于低能见度容易产生误报警。

因此：

对于 `visibility < 600` 的记录，不要删除，

而是将

```
visibility
```

修改为缺失值（NaN）。

---

In [21]:
df['visibility'] =df['visibility'].mask(df['visibility'] < 600)
df

   record_id site status  temperature  visibility
0        101  R34  ERROR           72       800.0
2        103  R35  ERROR           88         NaN
6        107  R34  ERROR           79         NaN
7        108  R35  ERROR           86       610.0
9        110  R34  ERROR           70         NaN

### 任务5

为了方便查看，

最终结果只保留：

- record_id
- site
- temperature
- visibility

四列。

保存为：

```python
result
```

---

In [22]:
result = df[['record_id','site','temperature','visibility']]
result

   record_id site  temperature  visibility
0        101  R34           72       800.0
2        103  R35           88         NaN
6        107  R34           79         NaN
7        108  R35           86       610.0
9        110  R34           70         NaN